### PR TITLE
Fix compatibility with TYPO3 v10 LTS

### PR DESCRIPTION
**Pull request by bnf**
And also avoid usage of deprecated code, to work with current TYPO3 master.

### CODE REVIEW

**Comment by bnf** [comment]
Note: I included a commit to avoid deprecated code in order to prepare for TYPO3 master. The reason is that we still have left-overs from EXT:rsaauth in current TYPO3 core (in frontend templates and TypeScript files) and to be able to test
or generalize these (e.. in order to drop explicit rsaauth references), we need a master-compatible rsaauth version.

**Comment by bihor** [comment]
I have tested this patch with version 10.0.2 (which still not work with TYPO3 10.4), but now I get this error:

(1/1) Symfony\Component\DependencyInjection\Exception\InvalidArgumentException

Expected to find class "TYPO3\CMS\Rsaauth\Backend\AbstractBackend" in file "/var/www/html/server/typo3conf/ext/rsaauth/Classes/Backend/AbstractBackend.php" while importing services from resource "../Classes/*", but it was not found! Check the namespace prefix used with the resource.

**Comment by bihor** [comment]
And when I delete the part from ext_localconf.php I get this error:

(1/1) Symfony\Component\DependencyInjection\Exception\InvalidArgumentException

Expected to find class "TYPO3\CMS\Rsaauth\EventHandler\ModifyPageLayoutOnLoginProviderSelection" in file "/var/www/html/server/typo3conf/ext/rsaauth/Classes/EventHandler/ModifyPageLayoutOnLoginProviderSelection.php" while importing services from resource "../Classes/*", but it was not found! Check the namespace prefix used with the resource.

**Comment by bnf** [comment]
Main conflicts have been fixed in https://github.com/FriendsOfTYPO3/rsaauth/commit/c0ab8fa6b6316f046401c7359ac574004798c224 and https://github.com/FriendsOfTYPO3/rsaauth/commit/fe66706ac544118911c6522271bf2277a649bafa

The commit to avoid deprecated code isn't that helpful, as v11.2 dropped support for rsaauth-hookin anyway with the following commit:

> 69397: [TASK] Remove possibility to use ext:rsaauth | https://review.typo3.org/c/Packages/TYPO3.CMS/+/69397

Therefore I'd rather close my pull request, instead of migrating to `ModifyPageLayoutOnLoginProviderSelectionEvent` for zero added value (v11 will not be possible anyway).

(We could reopen this one in case anyway decided to revert https://review.typo3.org/c/Packages/TYPO3.CMS/+/69397 for TYPO3 v11)

**Pull request closed without merging**
